Remove the workaround
SwedbankPay/swedbank-pay-woocommerce-core pull request #84
Opened 2022-10-09 14:17 UTC by olegisk

Remove workaround:
```php
// Workaround: don't set paymentUrl if there's "pay_for_order" page
        if (isset($_GET['pay_for_order'], $_GET['key'])) {
            $paymentUrl = null;
        }
```

2022-10-10 14:37 UTC, aait approved these changes

2022-10-10 15:14 UTC, asbjornu requested changes
PHP Mess Detector fails at the following:

```
/home/runner/work/swedbank-pay-woocommerce-core/swedbank-pay-woocommerce-core/src/SwedbankPay/Core/Library/Methods/Checkout.php:52  LongVariable  Avoid excessively long variable names like $generateRecurrenceToken. Keep variable name length under 20.
```

Please fix.

2022-10-11 07:46 UTC, olegisk commented
> PHP Mess Detector fails at the following:
> 
> ```
> /home/runner/work/swedbank-pay-woocommerce-core/swedbank-pay-woocommerce-core/src/SwedbankPay/Core/Library/Methods/Checkout.php:52  LongVariable  Avoid excessively long variable names like $generateRecurrenceToken. Keep variable name length under 20.
> ```
> 
> Please fix.

Fixed

2022-10-11 11:56 UTC, asbjornu approved these changes

2022-10-11 17:03 UTC, merged